// Lista oficială de localități din Republica Moldova, preluată din EVS Express
// (GetNomenclatures?type=localities) — sursa de adevăr pentru ce recunoaște
// curierul ca adresă de livrare validă. Regenerat cu scripts/fetch-moldova-localities.js.
export const MOLDOVA_LOCALITIES: readonly string[] = [
  "Abaclia",
  "Acui",
  "Agronomovca",
  "Alava",
  "Albina",
  "Albinetul Nou",
  "Albinetul Vechi",
  "Albineţul Vechi",
  "Albinita",
  "Albota de Jos",
  "Albota de Sus",
  "Alcedar",
  "Alexanderfeld",
  "Alexandreni",
  "Alexandresti",
  "Alexandrovca",
  "Alexandru cel Bun",
  "Alexandru Ioan Cuza",
  "Alexeevca",
  "Alexeuca",
  "Aluatu",
  "Alunis",
  "Andreevca",
  "Andrusul de Jos",
  "Andrusul de Sus",
  "Anenii Noi",
  "Anini",
  "Antonesti",
  "Antoneuca",
  "Antonovca",
  "Arionesti",
  "Armanca",
  "Artimonovca",
  "Avdarma",
  "Avrameni",
  "Baccealia",
  "Bacioi",
  "Bacioi, C",
  "Bacseni",
  "Badiceni",
  "Badicul Moldovenesc",
  "Badragii Noi",
  "Badragii Vechi",
  "Bahmut",
  "Bahmut (Statie Cale Ferata)",
  "Bahrinesti",
  "Bahu",
  "Baimaclia",
  "Baius",
  "Balabanesti",
  "Balabanu",
  "Balanesti",
  "Balanul Nou",
  "Balasesti",
  "Balasinesti",
  "Balatina",
  "Balauresti",
  "Balcauti",
  "Balceana",
  "Balinti",
  "Balintii Noi",
  "Balmaz",
  "Baltata",
  "Baltata de Sus",
  "Baltati",
  "Balti",
  "Banesti",
  "Banestii Noi",
  "Baraboi",
  "Barboieni",
  "Bardar",
  "Baroncea",
  "Baroncea Noua",
  "Basarabeasca",
  "Bascalia",
  "Batic",
  "Batir",
  "Baurci",
  "Baurci Moldoveni",
  "Baurci-Moldoveni",
  "Baxani",
  "Beleavinti",
  "Beleuti",
  "Berezlogi",
  "Berezovca",
  "Beriozchi",
  "Berlinti",
  "Besalma",
  "Besghioz",
  "Bestemac",
  "Bezeda",
  "Bezeni",
  "Bic",
  "Biesti",
  "Bilicenii Noi",
  "Bilicenii Vechi",
  "Birladeni",
  "Birnova",
  "Biruinta",
  "Bisericani",
  "Blesteni",
  "Blindesti",
  "Bobeica",
  "Bobletici",
  "Bobocica",
  "Bobulesti",
  "Bocancea-Schit",
  "Bocani",
  "Bocicauti",
  "Bocsa",
  "Bogdanesti",
  "Bogdanovca",
  "Bogdanovca Noua",
  "Bogdanovca Veche",
  "Boghenii Noi",
  "Boghenii Vechi",
  "Boghiceni",
  "Bogzesti",
  "Bolduresti",
  "Bolohan",
  "Boltun",
  "Bondareuca",
  "Borceag",
  "Borogani",
  "Boroseni",
  "Borosenii Noi",
  "Boscana",
  "Bosernita",
  "Botnaresti",
  "Botnarestii Noi",
  "Bozieni",
  "Braicau",
  "Braila",
  "Branesti",
  "Braniste",
  "Bratianovca",
  "Bratuleni",
  "Bratuseni",
  "Bratusenii Noi",
  "Bravicea",
  "Braviceni",
  "Breanova",
  "Brejeni",
  "Brezoaia",
  "Briceni",
  "Briceva",
  "Brinza",
  "Brinzeni",
  "Brinzenii Noi",
  "Brinzenii Vechi",
  "Bubuieci",
  "Buciumeni",
  "Buciumeni (Statie Cale Ferata)",
  "Buciusca",
  "Bucovat",
  "Bucovaţ",
  "Bucuria",
  "Buda",
  "Budai",
  "Budesti",
  "Budesti, C",
  "Bugeac",
  "Bujor",
  "Bulaiesti",
  "Bularda",
  "Bulboaca",
  "Bulboci",
  "Bulbocii Noi",
  "Bulgarica",
  "Bulhac",
  "Bumbata",
  "Buneti",
  "Burghelea",
  "Burlaceni",
  "Burlacu",
  "Burlanesti",
  "Bursuc",
  "Bursuceni",
  "Busauca",
  "Busila",
  "Buteni",
  "Butesti",
  "Butuceni",
  "Buţeni",
  "Buzduganii de Jos",
  "Buzduganii de Sus",
  "Buzdugeni",
  "Cabaiesti",
  "Cahul",
  "Caietu",
  "Cainari",
  "Cainari (Statie Cale Ferata)",
  "Cainarii Vechi",
  "Cairaclia",
  "Cajba",
  "Calaraseuca",
  "Calarasi",
  "Calfa",
  "Calfa Noua",
  "Calimanesti",
  "Calinesti",
  "Calmatui",
  "Calmatui, HN",
  "Calugar",
  "Camenca",
  "Camencea",
  "Camencuta",
  "Cania",
  "Cantemir",
  "Capaclia",
  "Capceac",
  "Caplani",
  "Capresti",
  "Capriana",
  "Carabetovca",
  "Carabiber",
  "Caracui",
  "Caracusenii Noi",
  "Caracusenii Vechi",
  "Carahasani",
  "Caraiman",
  "Carbalia",
  "Carbuna",
  "Carpineanca",
  "Carpineni",
  "Casunca",
  "Cateleni",
  "Catranic",
  "Catranic (Statie Cale Ferata)",
  "Causeni",
  "Cazaclia",
  "Cazanesti",
  "Cazangic",
  "Ceadir",
  "Ceadir-Lunga",
  "Cealic",
  "Ceapaevca",
  "Cenac",
  "Cenusa",
  "Ceparia",
  "Cepeleuti",
  "Cerlina",
  "Cernita",
  "Cernoleuca",
  "Ceroborta",
  "Cetireni",
  "Cheltuitori",
  "Chersac",
  "Chetris",
  "Chetrisul Nou",
  "Chetroasa",
  "Chetroseni",
  "Chetrosica Noua",
  "Chetrosica Veche",
  "Chetrosu",
  "Chilisoaia",
  "Chioselia",
  "Chioselia Mare",
  "Chioselia Rusa",
  "Chiperceni",
  "Chipesca",
  "Chirca",
  "Chircaiesti",
  "Chircaiestii Noi",
  "Chircani",
  "Chirianca",
  "Chiriet-Lunga",
  "Chirileni",
  "Chirilovca",
  "Chirsova",
  "Chiscareni",
  "Chisinau",
  "Chistelnita",
  "Chitcani",
  "Chitcanii Noi",
  "Chitcanii Vechi",
  "Chiţcanii Vechi",
  "Chiurt",
  "Cigirleni",
  "Cihoreni",
  "Cimiseni",
  "Cimislia",
  "Cimpul Drept",
  "Ciniseuti",
  "Ciniseuţi",
  "Cioara",
  "Ciobalaccia",
  "Ciobanca",
  "Ciobanovca",
  "Cioburciu",
  "Cioc-Maidan",
  "Ciocilteni",
  "Ciofu",
  "Ciolacu Nou",
  "Ciolacu Vechi",
  "Ciopleni",
  "Ciorescu",
  "Cioresti",
  "Ciorna",
  "Cioropcani",
  "Ciripcau",
  "Cirnateni",
  "Cirnatenii Noi",
  "Cirnesti",
  "Cirpesti",
  "Cisla",
  "Cislita-Prut",
  "Cismea",
  "Cismichioi",
  "Ciubara",
  "Ciuciuieni",
  "Ciuciulea",
  "Ciuciuleni",
  "Ciucur-Mingir",
  "Ciuflesti",
  "Ciuluc",
  "Ciulucani",
  "Ciumai",
  "Ciutesti",
  "Ciutulesti",
  "Cizlar",
  "Climauti",
  "Climautii de Jos",
  "Climauţii de Jos",
  "Cliscauti",
  "Clisova",
  "Clisova Noua",
  "Clococenii Vechi",
  "Clocusna",
  "Cneazevca",
  "Coada Iazului",
  "Cobani",
  "Cobilea",
  "Cobilea (Statie Cale Ferata)",
  "Cobusca Noua",
  "Cobusca Veche",
  "Cocieri",
  "Cociulia",
  "Cociulia Noua",
  "Codreanca",
  "Codreni",
  "Codrenii Noi",
  "Codru",
  "Codrul Nou",
  "Cogilniceni",
  "Cojusna",
  "Colibabovca",
  "Colibasi",
  "Colicauti",
  "Colonita",
  "Coloniţa",
  "Comarovca",
  "Comrat",
  "Comuna Bulboci",
  "Comuna Mihalaseni",
  "Condratesti",
  "Condrita",
  "Congaz",
  "Congazcicul de Jos",
  "Congazcicul de Sus",
  "Constantinesti",
  "Constantinovca",
  "Copaceni",
  "Copanca",
  "Copceac",
  "Corbu",
  "Corestauti",
  "Corestauţi",
  "Corjeuti",
  "Corjova",
  "Corlateni",
  "Cornesti",
  "Cornova",
  "Coroliovca",
  "Coropceni",
  "Corpaci",
  "Corten",
  "Cortenul Nou",
  "Cosauti",
  "Coscalia",
  "Coscodeni",
  "Coseni",
  "Cosernita",
  "Cosnita",
  "Cosniţa",
  "Costangalia",
  "Costesti",
  "Costuleni",
  "Cot",
  "Coteala",
  "Cotihana",
  "Cotiujeni",
  "Cotiujenii Mari",
  "Cotiujenii Mici",
  "Cotova",
  "Cotovca",
  "Cotovscova",
  "Cotul Morii",
  "Covurlui",
  "Cozesti",
  "Craciun",
  "Crasnaseni",
  "Crasnoarmeiscoe",
  "Cremenciug",
  "Cretoaia",
  "Creţoaia",
  "Cricova",
  "Crihana",
  "Crihana Veche",
  "Criscauti",
  "Cristesti",
  "Criuleni",
  "Criva",
  "Crocmaz",
  "Cruglic",
  "Cruzesti",
  "Cubolta",
  "Cucioaia",
  "Cucioaia Noua",
  "Cucoara",
  "Cuconestii Noi",
  "Cuconestii Vechi",
  "Cucuietii Noi",
  "Cucuietii Vechi",
  "Cucuruzeni",
  "Cucuruzenii de Sus",
  "Cuhnesti",
  "Cuhurestii de Jos",
  "Cuhurestii de Sus",
  "Cuizauca",
  "Cunicea",
  "Cupcini",
  "Cupcui",
  "Cuporani",
  "Curatura",
  "Curchi",
  "Curesnita",
  "Curesnita Noua",
  "Curtoaia",
  "Cuselauca",
  "Cusmirca",
  "Cuzmenii Vechi",
  "Dahnovici",
  "Damascani",
  "Danceni",
  "Dancu",
  "Danu",
  "Darcauti",
  "Darcautii Noi",
  "Decebal",
  "Delacau",
  "Dereneu",
  "Dermengi",
  "Dezghingea",
  "Dimitrova",
  "Dimitrovca",
  "Dingeni",
  "Discova",
  "Dobrogea",
  "Dobrogea Noua",
  "Dobrogea Veche",
  "Dobrusa",
  "Doina",
  "Dolinnoe",
  "Dolna",
  "Doltu",
  "Dominteni",
  "Domulgeni",
  "Donduseni",
  "Donici",
  "Dorotcaia",
  "Draganesti",
  "Draguseni",
  "Dragusenii Noi",
  "Drasliceni",
  "Drepcauti",
  "Drepcauţi",
  "Drochia",
  "Drojdieni",
  "Drujba",
  "Drujineni",
  "Druta",
  "Dubasari",
  "Dubasarii Vechi",
  "Dubna",
  "Dubovca",
  "Dudulesti",
  "Duma",
  "Dumbrava",
  "Dumbraveni",
  "Dumbravita",
  "Dumeni",
  "Dumitreni",
  "Durlesti",
  "Duruitoarea",
  "Duruitoarea Noua",
  "Dusmani",
  "Ecaterinovca",
  "Echimauti",
  "Edinet",
  "Edineţ",
  "Egoreni",
  "Egorovca",
  "Elenovca",
  "Elizaveta",
  "Elizavetovca",
  "Enichioi",
  "Ermoclia",
  "Etulia",
  "Etulia (Statie Cale Ferata)",
  "Etulia Noua",
  "Evghenievca",
  "Fagadau",
  "Fagureni",
  "Falesti",
  "Falestii Noi",
  "Fauresti",
  "Fedoreuca",
  "Ferapontievca",
  "Festelita",
  "Feteasca",
  "Fetesti",
  "Fetita",
  "Filipeni",
  "Fintina Alba",
  "Fintinita",
  "Fintiniţa",
  "Firladeni",
  "Firladenii Noi",
  "Flaminzeni",
  "Flocoasa",
  "Floreni",
  "Floresti",
  "Florica",
  "Floriceni",
  "Floricica",
  "Floritoaia Noua",
  "Floritoaia Veche",
  "Flutura",
  "Frasin",
  "Frasinesti",
  "Frumoasa",
  "Frumusica",
  "Frumusica Noua",
  "Frunza",
  "Frunzesti",
  "Fundul Galbenei",
  "Fundurii Noi",
  "Fundurii Vechi",
  "Furceni",
  "Fuzauca",
  "Gaidar",
  "Galaseni",
  "Galesti",
  "Galestii Noi",
  "Gangura",
  "Gaspar",
  "Gaureni",
  "Gauzeni",
  "Gavanoasa",
  "Gavrilovca",
  "Geamana",
  "Ghelauza",
  "Gherman",
  "Ghermanesti",
  "Ghetlova",
  "Ghidighici",
  "Ghiduleni",
  "Ghiliceni",
  "Ghindesti",
  "Ghioltosu",
  "Ghizdita (Statie Cale Ferata)",
  "Girbova",
  "Gisca",
  "Giurgiulesti",
  "Glinjeni",
  "Glodeni",
  "Goian",
  "Goianul Nou",
  "Goleni",
  "Gordinesti",
  "Gordinestii Noi",
  "Gornoe",
  "Gotesti",
  "Gradinita",
  "Gradiste",
  "Graseni",
  "Gratiesti",
  "Greblesti",
  "Greceni",
  "Gribova",
  "Grigorauca",
  "Grigoresti",
  "Grigorievca",
  "Grimancauti",
  "Grimesti",
  "Grinauti",
  "Grinauti (StatiaCaleFerat",
  "Grinauti-Moldova",
  "Grinauti-Raia",
  "Grinauţi-Raia",
  "Grozasca",
  "Grozesti",
  "Groznita",
  "Gura Bicului",
  "Gura Cainarului",
  "Gura Camencii",
  "Gura Galbenei",
  "Gura-Oituz",
  "Gvozdova",
  "Hadarauti",
  "Hadarauţi",
  "Hagichioi",
  "Hagimus",
  "Halahora de Jos",
  "Halahora de Sus",
  "Hanaseni",
  "Hanasenii Noi",
  "Hancauti",
  "Hancauţi",
  "Hansca",
  "Haragis",
  "Hasnasenii Mari",
  "Hasnasenii Noi",
  "Heciul Nou",
  "Heciul Vechi",
  "Helesteni",
  "Hijdieni",
  "Hiliuti",
  "Hincauti",
  "Hincesti",
  "Hirbovat",
  "Hirbovatul Nou",
  "Hircesti",
  "Hiriseni",
  "Hirjauca",
  "Hirova",
  "Hirtop",
  "Hirtopul Mare",
  "Hirtopul Mic",
  "Hitresti",
  "Hlina",
  "Hlinaia",
  "Hlinaia Mica",
  "Hoginesti",
  "Holercani",
  "Holosnita",
  "Holosnita Noua",
  "Holosniţa",
  "Homuteanovca",
  "Horesti",
  "Horjesti",
  "Horodca",
  "Horodiste",
  "Hristici",
  "Hristoforovca",
  "Hrubna Noua",
  "Hruseova",
  "Hrusova",
  "Hulboaca",
  "Huluboaia",
  "Humulesti",
  "Hutulu",
  "Huzun",
  "Iabloana",
  "Iachimeni",
  "Ialoveni",
  "Ialpug",
  "Ialpujeni",
  "Iargara",
  "Iarova",
  "Iasnaia Poleana",
  "Iepureni",
  "Iezarenii Noi",
  "Iezarenii Vechi",
  "Ignatei",
  "Ignaţei",
  "Ilenuta",
  "Iliciovca",
  "Inculet",
  "Inesti",
  "Inundeni",
  "Ion Voda",
  "Iordanovca",
  "Iorjnita",
  "Iorjniţa",
  "Isacova",
  "Isaicani",
  "Iscalau",
  "Iserlia",
  "Isnovat",
  "Iujnoe",
  "Iurceni",
  "Iurievca",
  "Ivancea",
  "Ivanesti",
  "Ivanovca",
  "Ivanovca Noua",
  "Izbiste",
  "Izvoare",
  "Izvoreni",
  "Japca",
  "Javgur",
  "Jeloboc",
  "Jevreni",
  "Joltai",
  "Jora de Jos",
  "Jora de Mijloc",
  "Jora de Sus",
  "Lalova",
  "Lapusna",
  "Larga",
  "Larga Noua",
  "Larga Veche",
  "Larguta",
  "Larguţa",
  "Lazo",
  "Lebedenco",
  "Leca",
  "Lelina",
  "Lencauti",
  "Lencauţi",
  "Leordoaia",
  "Leova",
  "Leuntea",
  "Leuseni",
  "Lidovca",
  "Limbenii Noi",
  "Limbenii Vechi",
  "Lingura",
  "Lipcani",
  "Lipceni",
  "Lipnic",
  "Lipovanca",
  "Lipovat",
  "Lipoveni",
  "Livezi",
  "Loganesti",
  "Logofteni",
  "Lopatica",
  "Lopatna",
  "Lopatnic",
  "Lozova",
  "Lucaceni",
  "Lucaseuca",
  "Lucesti",
  "Lugovoe",
  "Luminita",
  "Lunga",
  "Lupa-Recea",
  "Luparia",
  "Macaresti",
  "Macareuca",
  "Magdacesti",
  "Magura",
  "Magura Noua",
  "Magureanca",
  "Magurele",
  "Mahala",
  "Maiovca",
  "Maiscoe",
  "Malaesti",
  "Malaiesti",
  "Malaiestii Noi",
  "Malcauti",
  "Malcoci",
  "Malinovscoe",
  "Mana",
  "Manoilesti",
  "Manta",
  "Maramonovca",
  "Marandeni",
  "Marasesti",
  "Marcauti",
  "Marcautii Noi",
  "Marcauţi",
  "Marchet",
  "Marculesti",
  "Mardareuca",
  "Marianca de Jos",
  "Marianca de Sus",
  "Marienfeld",
  "Marinesti",
  "Marinici",
  "Martinesti",
  "Mascauti",
  "Mascauţi",
  "Mateuti",
  "Mateuţi",
  "Maximeni",
  "Maximovca",
  "Medeleni",
  "Medveja",
  "Meleseni",
  "Mereneşti",
  "Mereni",
  "Merenii Noi",
  "Mereseni",
  "Mereseuca",
  "Meseni",
  "Micauti",
  "Miciurin",
  "Miclesti",
  "Micleuseni",
  "Mihaileni",
  "Mihailenii Noi",
  "Mihailovca",
  "Mihalasa",
  "Mihalasa Noua",
  "Mihalaseni",
  "Mihuleni",
  "Milesti",
  "Milestii Mici",
  "Milestii Noi",
  "Mincenii de Jos",
  "Mincenii de Sus",
  "Mindic",
  "Mindra",
  "Mindresti",
  "Mindrestii Noi",
  "Mingir",
  "Minzatesti",
  "Mircesti",
  "Miresti",
  "Mirnoe",
  "Mirzaci",
  "Mirzesti",
  "Mirzoaia",
  "Misovca",
  "Mitoc",
  "Moara de Piatra",
  "Moara Domneasca",
  "Moldoveanca",
  "Molesti",
  "Molovata",
  "Molovata Noua",
  "Morenii Noi",
  "Morenii Vechi",
  "Morovaia",
  "Morozeni",
  "Mosana",
  "Moscovei",
  "Moseni",
  "Movileni",
  "Munteni",
  "Musaitu",
  "Musteata",
  "Napadeni",
  "Napadova",
  "Naslavcea",
  "Natalievca",
  "Navirnet",
  "Navirneţ",
  "Neculaieuca",
  "Negrea",
  "Negresti",
  "Negureni",
  "Negurenii Noi",
  "Negurenii Vechi",
  "Nemteni",
  "Nicolaevca",
  "Nicoreni",
  "Nihoreni",
  "Nimereuca",
  "Nimoreni",
  "Niorcani",
  "Niscani",
  "Nisporeni",
  "Nistreni",
  "Noroceni",
  "Novaci",
  "Novaia Nicolaevca",
  "Novosiolovca",
  "Nucareni",
  "Obeja Veche",
  "Obileni",
  "Obreja Noua",
  "Obreja Veche",
  "Ochiul Alb",
  "Ochiul Ros",
  "Oclanda",
  "Ocnita",
  "Ocnita-Razesi",
  "Ocnita-Tarani",
  "Ocniţa",
  "Ocolina",
  "Octeabriscoe",
  "Odaia",
  "Odobesti",
  "Ohrincea",
  "Olanesti",
  "Oliscani",
  "Onesti",
  "Oniscani",
  "Onitcani",
  "Oniţcani",
  "Opaci",
  "Or",
  "Orac",
  "Ordasei",
  "Orehovca",
  "Orhei",
  "Oricova",
  "Otac",
  "Otaci",
  "Oxentea",
  "Paharniceni",
  "Paicu",
  "Paladea",
  "Palanca",
  "Palaria",
  "Panasesti",
  "Papauti",
  "Parcani",
  "Parcova",
  "Paruceni",
  "Pascani",
  "Pascauti",
  "Paulesti",
  "Paustova",
  "Pavlovca",
  "Peciste",
  "Pelinei",
  "Pelinia",
  "Pelivan",
  "Pepeni",
  "Pepenii Noi",
  "Pereni",
  "Pererita",
  "Peresecina",
  "Pervomaisc",
  "Pervomaiscoe",
  "Peticeni",
  "Petreni",
  "Petresti",
  "Petresti (Statie Cale Ferata)",
  "Petropavlovca",
  "Petrovca",
  "Petrunea",
  "Petruseni",
  "Piatra",
  "Piatra Alba",
  "Picus",
  "Pietrosu",
  "Pietrosul Nou",
  "Pinzareni",
  "Pinzarenii Noi",
  "Pirita",
  "Pirjolteni",
  "Pirjota",
  "Pirlita",
  "Pirliţa",
  "Piscaresti",
  "Pistruieni",
  "Pistruienii Noi",
  "Pitesti",
  "Pitusca",
  "Pivniceni",
  "Pleseni",
  "Plop",
  "Plop-Stiubei",
  "Plopi",
  "Pociumbauti",
  "Pociumbeni",
  "Pocrovca",
  "Pocsesti",
  "Podgoreni",
  "Podul Lung",
  "Poganesti",
  "Pohoarna",
  "Pohorniceni",
  "Pohrebea",
  "Pohrebeni",
  "Poiana",
  "Pojareni",
  "Pojarna",
  "Pompa",
  "Popeasca",
  "Popestii de Jos",
  "Popestii de Sus",
  "Popestii Noi",
  "Popovca",
  "Porumbeni",
  "Porumbesti",
  "Porumbrei",
  "Prajila",
  "Prepelita",
  "Prepeliţa",
  "Pripiceni-Curchi",
  "Pripiceni-Razesi",
  "Prisaca",
  "Prodanesti",
  "Prodanestii Vechi",
  "Proscureni",
  "Pruteni",
  "Puhaceni",
  "Puhoi",
  "Purcari",
  "Putinesti",
  "Putintei",
  "Racaria",
  "Raciula",
  "Racovat",
  "Racovaţ",
  "Raculesti",
  "Radeni",
  "Radenii Vechi",
  "Radoaia",
  "Radulenii Noi",
  "Radulenii Vechi",
  "Ramazan",
  "Rascaieti",
  "Rascaietii Noi",
  "Raspopeni",
  "Rassvet",
  "Ratus",
  "Rautel",
  "Rautelul Nou",
  "Rauţel",
  "Razalai",
  "Razeni",
  "Recea",
  "Recesti",
  "Redi - Ceresnovaţ",
  "Redi-Ceresnovat",
  "Rediul de Jos",
  "Rediul de Sus",
  "Rediul Mare",
  "Regina Maria",
  "Reteni",
  "Reteni-Vasileuti",
  "Reteni-Vasileuţi",
  "Revaca",
  "Rezina",
  "Ringaci",
  "Riscani",
  "Riscova",
  "Risipeni",
  "Rogojeni",
  "Rogojeni (Statie Cale Ferata)",
  "Romanesti",
  "Romanovca",
  "Roscani",
  "Roscanii de Jos",
  "Roscanii de Sus",
  "Rosietici",
  "RosieticiiVechi",
  "Rosita",
  "Rosu",
  "Rotunda",
  "Rublenita",
  "Rublenita Noua",
  "Rudi",
  "Rujnita",
  "Rumeantev",
  "Rumeanţev",
  "Rusca",
  "Ruseni",
  "Rusestii Noi",
  "Rusestii Vechi",
  "Ruslanovca",
  "Saca",
  "Sacarovca",
  "Sadaclia",
  "Sadic",
  "Sadova",
  "Sadovoe",
  "Sagaidac",
  "Sagaidacul de Sus",
  "Sagaidacul Nou",
  "Saghieni",
  "Saharna",
  "Saharna Noua",
  "Saiti",
  "Salcia",
  "Salcuta",
  "Salcuta Noua",
  "Salcuţa",
  "Salvirii Noi",
  "Salvirii Vechi",
  "Samalia",
  "Samananca",
  "Samascani",
  "Samurza",
  "Sanatauca",
  "Saptebani",
  "Sarata Noua",
  "Sarata Veche",
  "Sarata-Galbena",
  "Sarata-Mereseni",
  "Sarata-Razesi",
  "Sarateni",
  "Saratenii Noi",
  "Saratenii Vechi",
  "Saratica Noua",
  "Saratica Veche",
  "Saseni",
  "Satuc",
  "Satul Nou",
  "Sauca",
  "Scaieni",
  "Schineni",
  "Schinenii Noi",
  "Schinoasa",
  "Schinosica",
  "Scoreni",
  "Scorteni",
  "Scorţeni",
  "Sculeni",
  "Scumpia",
  "Secareni",
  "Secarenii Noi",
  "Selemet",
  "Seliste",
  "Selistea Noua",
  "Selisteni",
  "Semeni",
  "Semionovca",
  "Sendreni",
  "Septelici",
  "Sercani",
  "Sergheuca",
  "Serghieni",
  "Serpeni",
  "Sestaci",
  "Sevirova",
  "Sicovat",
  "Sinesti",
  "Singera",
  "Singerei",
  "Singereii Noi",
  "Singureni",
  "Sipca",
  "Sipoteni",
  "Sirauti",
  "Sirbesti",
  "Sircova",
  "Sireti",
  "Sirma",
  "Sirota",
  "Siscani",
  "Slobodca",
  "Slobozia",
  "Slobozia Mare",
  "Slobozia Noua",
  "Slobozia Varancau",
  "Slobozia-Chiscareni",
  "Slobozia-Cremene",
  "Slobozia-Dusca",
  "Slobozia-Hodorogea",
  "Slobozia-Horodiste",
  "Slobozia-Magura",
  "Slobozia-Medveja",
  "Slobozia-Recea",
  "Slobozia-Sirauti",
  "Slobozia-Varancau",
  "Sloveanca",
  "Sobari",
  "Socii Noi",
  "Socii Vechi",
  "Sociteni",
  "Socola",
  "Socoleni",
  "Sofia",
  "Sofievca",
  "Sofranovca",
  "Sofrincani",
  "Solcani",
  "Soldanesti",
  "Solonceni",
  "Solonet",
  "Soltanesti",
  "Soltoaia",
  "Soroca",
  "Speia",
  "Spicoasa",
  "Stalinesti",
  "Stantia Vulcanesti",
  "Stauceni",
  "Stefan Voda",
  "Stefanesti",
  "Stejareni",
  "Step-Soci",
  "Stetcani",
  "Stircea",
  "Stirceni",
  "Stiubeieni",
  "Stohnaia",
  "Stoianovca",
  "Stoicani",
  "Stolniceni",
  "Straisteni",
  "Straseni",
  "Strimbeni",
  "Sturzeni",
  "Sturzovca",
  "Sudarca",
  "Suhat",
  "Suhuluceni",
  "Sumna",
  "Surchiceni",
  "Suri",
  "Suric",
  "Surii Noi",
  "Suruceni",
  "Susleni",
  "Suvorovca",
  "Sverdiac",
  "Sverida",
  "Svetlii",
  "Şaptebani",
  "Şeptelici",
  "Şerpeni",
  "Şipca",
  "Şirauţi",
  "Şiscani",
  "Ştefan Voda",
  "Ştefanesti",
  "Tabani",
  "Tabara",
  "Tahnauti",
  "Talaiesti",
  "Talmaza",
  "Tambula",
  "Tanatari",
  "Tanatarii Noi",
  "Tapoc",
  "Taraclia",
  "Taraclia de Salcie",
  "Tarancuta",
  "Tarasova",
  "Tareuca",
  "Tarigrad",
  "Tartaul",
  "Tartaul de Salcie",
  "Tataraseni",
  "Tatarauca Noua",
  "Tatarauca Veche",
  "Tataresti",
  "Taul",
  "Taura Noua",
  "Taura Veche",
  "Taxobeni",
  "Telenesti",
  "Teleseu",
  "Teleseuca",
  "Teleseuca Noua",
  "Telita",
  "Telita Noua",
  "Temeleuti",
  "Tepilova",
  "Terebna",
  "Tescureni",
  "Tetcani",
  "Tibirica",
  "Tiganca",
  "Tiganca Noua",
  "Tiganesti",
  "Tigheci",
  "Tighina (Bender)",
  "Tighira",
  "Tintareni",
  "Tipala",
  "Tiplesti",
  "Tipletesti",
  "Tipordei",
  "Tipova",
  "Tira",
  "Tira (Statie Cale Ferata)",
  "Tiraspol",
  "Tirgul-Vertiujeni",
  "Tirnova",
  "Tirsitei",
  "Tirzieni",
  "Toceni",
  "Tochile-Raducani",
  "Tocuz",
  "Todiresti",
  "Tohatin",
  "Tolica",
  "Tolocanesti",
  "Tomai",
  "Tomaiul Nou",
  "Tomestii Noi",
  "Tomestii Vechi",
  "Topala",
  "Trebisauti",
  "Trebujeni",
  "Trestieni",
  "Tretesti",
  "Tricolici",
  "Trifanesti",
  "Trifauti",
  "Trifesti",
  "Trifestii Noi",
  "Trinca",
  "Troian",
  "Troita",
  "Troita Noua",
  "Troitcoe",
  "Truseni",
  "Truseni, C",
  "Tudora",
  "Tudoresti",
  "Tuzara",
  "Tvardita",
  "Tvardiţa",
  "Ţambula",
  "Ţaul",
  "Ţiganca",
  "Ţinţareni",
  "Ţipala",
  "Ţiplesti",
  "Ucrainca",
  "Ulmu",
  "Unchitesti",
  "Unchitesti (Statie Cale Ferata)",
  "Ungheni",
  "Unguri",
  "Unteni",
  "Untesti",
  "Ursari",
  "Ursoaia",
  "Ursoaia Noua",
  "Ustia",
  "Usurei",
  "Vadeni",
  "Vadul lui Isac",
  "Vadul lui Voda",
  "Vadul-Leca",
  "Vadul-Leca Nou",
  "Vadul-Rascov",
  "Vaduleni",
  "Valcinet",
  "Valea",
  "Valea Colonitei",
  "Valea Florii",
  "Valea lui Vlad",
  "Valea Mare",
  "Valea Nirnovei",
  "Valea Norocului",
  "Valea Perjei",
  "Valea Radoaiei",
  "Valea Rusului",
  "Valea Satului",
  "Valea Verde",
  "Valea-Trestieni",
  "Valeni",
  "Vancicauti",
  "Vantina",
  "Vantina Mica",
  "Varancau",
  "Varatic",
  "Varnita",
  "Varniţa",
  "Varvareuca",
  "Varzaresti",
  "Varzarestii Noi",
  "Vascauti",
  "Vasieni",
  "Vasilcau",
  "Vasileuti",
  "Vasilievca",
  "Vatici",
  "Vatra",
  "Verejeni",
  "Vertiujeni",
  "Veverita",
  "Victoria",
  "Victorovca",
  "Viisoara",
  "Vilcele",
  "Vinatori",
  "Vinogradovca",
  "Viprova",
  "Viscauti",
  "Viscauţi",
  "Visniovca",
  "Visoca",
  "Vladimireuca",
  "Vladimirovca",
  "Voinescu",
  "Voinova",
  "Volintiri",
  "Voloave",
  "Volodeni",
  "Volovita",
  "Vorniceni",
  "Vorotet",
  "Vozneseni",
  "Vranesti",
  "Vulcanesti",
  "Vulpesti",
  "Zabriceni",
  "Zagarancea",
  "Zahareuca",
  "Zahoreni",
  "Zahorna",
  "Zaicana",
  "Zaicani",
  "Zaicanii Noi",
  "Zaim",
  "Zaim (Statie Cale Ferata)",
  "Zaluceni",
  "Zamciogi",
  "Zarojeni",
  "Zastinca",
  "Zazulenii Noi",
  "Zazulenii Vechi",
  "Zberoaia",
  "Zgardesti",
  "Zgurita",
  "Zimbreni",
  "Zirnesti",
  "Zloti (Statie Cale Ferata)",
  "Zolonceni",
  "Zolotievca",
  "Zorile",
  "Zubresti",
  "Zviozdocica"
];
